In [1]:
import os
import numpy as np
import pandas as pd
import nltk
import plotly.express as px
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from wordcloud import WordCloud,STOPWORDS
from bs4 import BeautifulSoup
import re,string,unicodedata

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB


from sklearn.model_selection import train_test_split
from sklearn.metrics import  accuracy_score, confusion_matrix,classification_report


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kartha96/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/kartha96/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /Users/kartha96/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
data=pd.read_csv('IMDB Dataset.csv')
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
data.drop_duplicates(inplace = True)

In [4]:
stop = stopwords.words('english')
wl = WordNetLemmatizer()


In [5]:
mapping = {"ain't": "is not", "aren't": "are not","can't": "cannot",
           "'cause": "because", "could've": "could have", "couldn't": "could not",
           "didn't": "did not",  "doesn't": "does not", "don't": "do not", "hadn't": "had not",
           "hasn't": "has not", "haven't": "have not", "he'd": "he would","he'll": "he will",
           "he's": "he is", "how'd": "how did", "how'd'y": "how do you", "how'll": "how will",
           "how's": "how is",  "I'd": "I would", "I'd've": "I would have", "I'll": "I will",
           "I'll've": "I will have","I'm": "I am", "I've": "I have", "i'd": "i would",
           "i'd've": "i would have", "i'll": "i will",  "i'll've": "i will have",
           "i'm": "i am", "i've": "i have", "isn't": "is not", "it'd": "it would",
           "it'd've": "it would have", "it'll": "it will", "it'll've": "it will have",
           "it's": "it is", "let's": "let us", "ma'am": "madam", "mayn't": "may not",
           "might've": "might have","mightn't": "might not","mightn't've": "might not have",
           "must've": "must have", "mustn't": "must not", "mustn't've": "must not have",
           "needn't": "need not", "needn't've": "need not have","o'clock": "of the clock",
           "oughtn't": "ought not", "oughtn't've": "ought not have", "shan't": "shall not",
           "sha'n't": "shall not", "shan't've": "shall not have", "she'd": "she would",
           "she'd've": "she would have", "she'll": "she will", "she'll've": "she will have",
           "she's": "she is", "should've": "should have", "shouldn't": "should not",
           "shouldn't've": "should not have", "so've": "so have","so's": "so as", "this's": "this is",
           "that'd": "that would", "that'd've": "that would have", "that's": "that is",
           "there'd": "there would", "there'd've": "there would have", "there's": "there is",
           "here's": "here is","they'd": "they would", "they'd've": "they would have",
           "they'll": "they will", "they'll've": "they will have", "they're": "they are",
           "they've": "they have", "to've": "to have", "wasn't": "was not", "we'd": "we would",
           "we'd've": "we would have", "we'll": "we will", "we'll've": "we will have",
           "we're": "we are", "we've": "we have", "weren't": "were not",
           "what'll": "what will", "what'll've": "what will have","what're": "what are",
           "what's": "what is", "what've": "what have", "when's": "when is", "when've": "when have",
           "where'd": "where did", "where's": "where is", "where've": "where have", "who'll": "who will",
           "who'll've": "who will have", "who's": "who is", "who've": "who have", "why's": "why is",
           "why've": "why have", "will've": "will have", "won't": "will not", "won't've": "will not have",
           "would've": "would have", "wouldn't": "would not", "wouldn't've": "would not have",
           "y'all": "you all", "y'all'd": "you all would","y'all'd've": "you all would have",
           "y'all're": "you all are","y'all've": "you all have","you'd": "you would",
           "you'd've": "you would have", "you'll": "you will", "you'll've": "you will have",
           "you're": "you are", "you've": "you have" }

In [6]:
def clean_text(text,lemmatize = True):
    soup = BeautifulSoup(text, "html.parser") #remove html tags
    text = soup.get_text()
    text = ' '.join([mapping[t] if t in mapping else t for t in text.split(" ")])
    text = re.sub(r'\.(?=\S)', '. ',text) #add space after full stop
    text = re.sub(r'http\S+', '', text) #remove urls
    text = "".join([word.lower() for word in text if word not in string.punctuation]) #remove punctuation
    #tokens = re.split('\W+', text) #create tokens
    if lemmatize:
        text = " ".join([wl.lemmatize(word) for word in text.split() if word not in stop and word.isalpha()]) #lemmatize
    else:
        text = " ".join([word for word in text.split() if word not in stop and word.isalpha()])
    return text

In [7]:
data_copy = data.copy()

In [8]:
data['review']=data['review'].apply(clean_text,lemmatize = True)

/var/folders/5b/cmxfzbyx2bl_h9g6lj3qcjhc0000gn/T/ipykernel_68967/53484750.py:2: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(text, "html.parser") #remove html tags


In [9]:
data.sentiment = [ 1 if each == "positive" else 0 for each in data.sentiment]

In [10]:
def get_words(text):
    words = []
    for i in text:
        for j in i.split():
            words.append(j.strip())
    return words
word = get_words(data.review)

In [11]:
from collections import Counter
counter = Counter(word)
most_common = counter.most_common(10)
most_common = pd.DataFrame(most_common,columns = ['word','count'])
most_common

word   count
0      movie  100605
1       film   91130
2        one   53525
3       like   39746
4       time   30091
5      would   30037
6       good   28905
7  character   27801
8      story   24600
9       even   24440

In [12]:
X=data['review']
Y=data['sentiment']

In [13]:
vect=TfidfVectorizer(analyzer='word',ngram_range=(1,2))
X_vect=vect.fit_transform(data['review'])

In [14]:
x_train,x_test,y_train,y_test=train_test_split(X_vect,Y,test_size=0.2,random_state=42)

In [15]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
p1=lr.predict(x_test)
s1=accuracy_score(y_test,p1)
print("Logistic Regression Accuracy :", "{:.2f}%".format(100*s1))

Logistic Regression Accuracy : 88.52%


In [16]:
print(confusion_matrix(y_test,p1))
print('\n')
print(classification_report(y_test,p1))

[[4264  675]
 [ 463 4515]]


              precision    recall  f1-score   support

           0       0.90      0.86      0.88      4939
           1       0.87      0.91      0.89      4978

    accuracy                           0.89      9917
   macro avg       0.89      0.89      0.89      9917
weighted avg       0.89      0.89      0.89      9917



In [17]:
mnb= MultinomialNB()
mnb.fit(x_train,y_train)
n1=mnb.predict(x_test)
m1=accuracy_score(y_test,n1)
print("Multinomial Naive Bayes Classifier Accuracy :", "{:.2f}%".format(100*m1))

Multinomial Naive Bayes Classifier Accuracy : 88.45%


In [18]:
print(confusion_matrix(y_test,n1))
print('\n')
print(classification_report(y_test,n1))

[[4342  597]
 [ 548 4430]]


              precision    recall  f1-score   support

           0       0.89      0.88      0.88      4939
           1       0.88      0.89      0.89      4978

    accuracy                           0.88      9917
   macro avg       0.88      0.88      0.88      9917
weighted avg       0.88      0.88      0.88      9917



In [19]:
linear_svc = LinearSVC(penalty='l2',loss = 'hinge')
linear_svc.fit(x_train,y_train)
p2=linear_svc.predict(x_test)
s2=accuracy_score(y_test,p2)
print("Linear Support Vector Classifier Accuracy :", "{:.2f}%".format(100*s2))

/Users/kartha96/anaconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Linear Support Vector Classifier Accuracy : 90.32%


In [20]:
print(confusion_matrix(y_test,p2))
print('\n')
print(classification_report(y_test,p2))

[[4388  551]
 [ 409 4569]]


              precision    recall  f1-score   support

           0       0.91      0.89      0.90      4939
           1       0.89      0.92      0.90      4978

    accuracy                           0.90      9917
   macro avg       0.90      0.90      0.90      9917
weighted avg       0.90      0.90      0.90      9917

