In [1]:
import os
import numpy as np
import pandas as pd
import nltk
import plotly.express as px
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from wordcloud import WordCloud,STOPWORDS
from bs4 import BeautifulSoup
import re,string,unicodedata

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB


from sklearn.model_selection import train_test_split
from sklearn.metrics import  accuracy_score, confusion_matrix,classification_report


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kartha96/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/kartha96/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /Users/kartha96/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
data1=pd.read_csv('first_part.csv')
data1.head()

Unnamed: 0                                   shortened_review  sentiment  \
0           0  one reviewer mentioned watching oz episode hoo...          1   
1           1  wonderful little production filming technique ...          1   
2           2  thought wonderful way spend time hot summer we...          1   
3           3  basically family little boy jake think zombie ...          0   
4           4  petter matteis love time money visually stunni...          1   

   word count2  
0           54  
1           28  
2           28  
3           21  
4           41

In [3]:
X=data1['shortened_review']
Y=data1['sentiment']

In [4]:
vect=TfidfVectorizer()
X=vect.fit_transform(data1['shortened_review'])

In [5]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

In [6]:
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
p1 = logreg.predict(x_test)
s1= accuracy_score(p1, y_test)
print("Test accuracy: {:.2f}%".format(s1*100))

Test accuracy: 80.36%


In [7]:
print(confusion_matrix(y_test,p1))
print("\n")
print(classification_report(y_test,p1))

[[5740 1664]
 [1258 6213]]


              precision    recall  f1-score   support

           0       0.82      0.78      0.80      7404
           1       0.79      0.83      0.81      7471

    accuracy                           0.80     14875
   macro avg       0.80      0.80      0.80     14875
weighted avg       0.80      0.80      0.80     14875



In [8]:
svc = LinearSVC()
svc.fit(x_train, y_train)
r1 = svc.predict(x_test)
t1 = accuracy_score(r1, y_test)
print("Test accuracy: {:.2f}%".format(t1*100))

/Users/kartha96/anaconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Test accuracy: 79.88%


In [9]:
print(confusion_matrix(y_test, r1))
print("\n")
print(classification_report(y_test,r1))

[[5773 1631]
 [1362 6109]]


              precision    recall  f1-score   support

           0       0.81      0.78      0.79      7404
           1       0.79      0.82      0.80      7471

    accuracy                           0.80     14875
   macro avg       0.80      0.80      0.80     14875
weighted avg       0.80      0.80      0.80     14875



In [10]:
mnb= MultinomialNB()
mnb.fit(x_train,y_train)
n1=mnb.predict(x_test)
m1=accuracy_score(y_test,n1)
print("Multinomial Naive Bayes Classifier Accuracy :", "{:.2f}%".format(100*m1))

Multinomial Naive Bayes Classifier Accuracy : 79.64%


In [11]:
print(confusion_matrix(y_test, n1))
print("\n")
print(classification_report(y_test, n1))

[[5876 1528]
 [1501 5970]]


              precision    recall  f1-score   support

           0       0.80      0.79      0.80      7404
           1       0.80      0.80      0.80      7471

    accuracy                           0.80     14875
   macro avg       0.80      0.80      0.80     14875
weighted avg       0.80      0.80      0.80     14875



In [12]:
data2=pd.read_csv('second_part.csv')
data2.head()

Unnamed: 0                                  shortened_review2  sentiment  \
0           0  cell glass front face inwards privacy high age...          1   
1           1  seamless editing guided reference williams dia...          1   
2           2  disappointed realize match point risk addictio...          1   
3           3  zombie ok first going make film must decide th...          0   
4           4  character meet connect one connected one way a...          1   

   word count2  
0           55  
1           29  
2           29  
3           22  
4           42

In [13]:
X=data2['shortened_review2']
Y=data2['sentiment']

In [14]:
vect=TfidfVectorizer()
X=vect.fit_transform(data2['shortened_review2'])

In [15]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

In [16]:
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
p2 = logreg.predict(x_test)
s2 = accuracy_score(p2, y_test)
print("Test accuracy: {:.2f}%".format(s2*100))

Test accuracy: 79.40%


In [17]:
print(confusion_matrix(y_test,p2))
print("\n")
print(classification_report(y_test,p2))

[[5705 1699]
 [1365 6106]]


              precision    recall  f1-score   support

           0       0.81      0.77      0.79      7404
           1       0.78      0.82      0.80      7471

    accuracy                           0.79     14875
   macro avg       0.79      0.79      0.79     14875
weighted avg       0.79      0.79      0.79     14875



In [18]:
svc = LinearSVC()
svc.fit(x_train, y_train)
r2 = svc.predict(x_test)
t2 = accuracy_score(r2, y_test)
print("Test accuracy: {:.2f}%".format(t2*100))

/Users/kartha96/anaconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Test accuracy: 78.76%


In [19]:
print(confusion_matrix(y_test, r2))
print("\n")
print(classification_report(y_test, r2))

[[5742 1662]
 [1498 5973]]


              precision    recall  f1-score   support

           0       0.79      0.78      0.78      7404
           1       0.78      0.80      0.79      7471

    accuracy                           0.79     14875
   macro avg       0.79      0.79      0.79     14875
weighted avg       0.79      0.79      0.79     14875



In [20]:
mnb= MultinomialNB()
mnb.fit(x_train,y_train)
n2=mnb.predict(x_test)
m2=accuracy_score(y_test,n2)
print("Multinomial Naive Bayes Classifier Accuracy :", "{:.2f}%".format(100*m2))

Multinomial Naive Bayes Classifier Accuracy : 78.87%


In [21]:
print(confusion_matrix(y_test, n2))
print("\n")
print(classification_report(y_test, n2))

[[5934 1470]
 [1673 5798]]


              precision    recall  f1-score   support

           0       0.78      0.80      0.79      7404
           1       0.80      0.78      0.79      7471

    accuracy                           0.79     14875
   macro avg       0.79      0.79      0.79     14875
weighted avg       0.79      0.79      0.79     14875



In [22]:
data3=pd.read_csv('third_part.csv')
data3.head()

Unnamed: 0                                  shortened_review3  sentiment  \
0           0  saw struck nasty surreal could say ready watch...          1   
1           1  guard rather use traditional dream technique r...          1   
2           2  impressed scarlet johanson managed tone sexy i...          1   
3           3  ruin film expected see boogeyman similar movie...          0   
4           4  human relation find sincere fulfillment one di...          1   

   word count3  
0           54  
1           28  
2           28  
3           21  
4           41

In [23]:
X=data3['shortened_review3']
Y=data3['sentiment']

In [24]:
vect=TfidfVectorizer()
X=vect.fit_transform(data3['shortened_review3'])

In [25]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

In [26]:
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
p3 = logreg.predict(x_test)
s3 = accuracy_score(p3, y_test)
print("Test accuracy: {:.2f}%".format(s3*100))

Test accuracy: 81.55%


In [27]:
print(confusion_matrix(y_test,p3))
print("\n")
print(classification_report(y_test, p3))

[[5905 1499]
 [1245 6226]]


              precision    recall  f1-score   support

           0       0.83      0.80      0.81      7404
           1       0.81      0.83      0.82      7471

    accuracy                           0.82     14875
   macro avg       0.82      0.82      0.82     14875
weighted avg       0.82      0.82      0.82     14875



In [28]:
svc = LinearSVC()
svc.fit(x_train, y_train)
r3 = svc.predict(x_test)
t3 = accuracy_score(r3, y_test)
print("Test accuracy: {:.2f}%".format(t3*100))

/Users/kartha96/anaconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Test accuracy: 80.93%


In [29]:
print(confusion_matrix(y_test,r3))
print("\n")
print(classification_report(y_test,r3))

[[5905 1499]
 [1337 6134]]


              precision    recall  f1-score   support

           0       0.82      0.80      0.81      7404
           1       0.80      0.82      0.81      7471

    accuracy                           0.81     14875
   macro avg       0.81      0.81      0.81     14875
weighted avg       0.81      0.81      0.81     14875



In [30]:
mnb= MultinomialNB()
mnb.fit(x_train,y_train)
n3=mnb.predict(x_test)
m3=accuracy_score(y_test,n3)
print("Multinomial Naive Bayes Classifier Accuracy :", "{:.2f}%".format(100*m3))

Multinomial Naive Bayes Classifier Accuracy : 80.84%


In [31]:
print(confusion_matrix(y_test, n3))
print("\n")
print(classification_report(y_test, n3))

[[5998 1406]
 [1444 6027]]


              precision    recall  f1-score   support

           0       0.81      0.81      0.81      7404
           1       0.81      0.81      0.81      7471

    accuracy                           0.81     14875
   macro avg       0.81      0.81      0.81     14875
weighted avg       0.81      0.81      0.81     14875

